# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs_realtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gtfs_realtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gtfs_realtime.proto\x12\x10transit_realtime\"i\n\x0b\x46\x65\x65\x64Message\x12,\n\x06header\x18\x01 \x02(\x0b\x32\x1c.transit_realtime.FeedHeader\x12,\n\x06\x65ntity\x18\x02 \x03(\x0b\x32\x1c.transit_realtime.FeedEntity\">\n\nFeedHeader\x12\x1d\n\x15gtfs_realtime_version\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"K\n\nFeedEntity\x12\n\n\x02id\x18\x01 \x02(\t\x12\x31\n\x0btrip_update\x18\x03 \x01(\x0b\x32\x1c.transit_realtime.TripUpdate\"x\n\nTripUpdate\x12.\n\x04trip\x18\x01 \x02(\x0b\x32 .transit_realtime.TripDescriptor\x12:\n\x10stop_time_update\x18\x02 \x03(\x0b\x32 .transit_realtime.StopTimeUpdate\"J\n\x0eTripDescriptor\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x10\n\x08route_id\x18\x05 \x01(\t\x12\x15\n\rtrip_headsign\x18\x06 \x01(\t\"\x9e\x01\n\x0eStopTimeUpdate\x12\x15\n\rstop_sequence\x18\x01 \x01(\r\x12\x0f\n\x07stop_id\x18\x04 \x01(\t\x12\x30\n\x07\x61rrival\x18\x02 \x01(\x0b\x32\x1f.transit_realtime.StopTimeEvent\x12\x32\n\tdeparture\x18\x03 \x01(\x0b\x32\x1f.transit_realtime.StopTimeEvent\",\n\rStopTimeEvent\x12\r\n\x05\x64\x65lay\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gtfs_realtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDMESSAGE']._serialized_start=41
  _globals['_FEEDMESSAGE']._serialized_end=146
  _globals['_FEEDHEADER']._serialized_start=148
  _globals['_FEEDHEADER']._serialized_end=210
  _globals['_FEEDENTITY']._serialized_start=212
  _globals['_FEEDENTITY']._serialized_end=287
  _globals['_TRIPUPDATE']._serialized_start=289
  _globals['_TRIPUPDATE']._serialized_end=409
  _globals['_TRIPDESCRIPTOR']._serialized_start=411
  _globals['_TRIPDESCRIPTOR']._serialized_end=485
  _globals['_STOPTIMEUPDATE']._serialized_start=488
  _globals['_STOPTIMEUPDATE']._serialized_end=646
  _globals['_STOPTIMEEVENT']._serialized_start=648
  _globals['_STOPTIMEEVENT']._serialized_end=692
# @@protoc_insertion_point(module_scope)
